"""Books_read ids single

Revision ID: 18cdeb869f28
Revises: 69768af72ffd
Create Date: 2022-02-19 12:00:50.796508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cdeb869f28'
down_revision = '69768af72ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_readers', 'books_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books_readers', 'readers_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_readers', 'readers_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books_readers', 'books_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
