"""Adding pages field into books

Revision ID: 9a33f19bead7
Revises: 0ee6ca8a0e60
Create Date: 2022-02-18 21:42:02.901412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a33f19bead7'
down_revision = '0ee6ca8a0e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pages')
    # ### end Alembic commands ###
