"""Books_read ids single

Revision ID: b404f1bd0e2d
Revises: 18cdeb869f28
Create Date: 2022-02-19 12:01:13.586091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b404f1bd0e2d'
down_revision = '18cdeb869f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_readers', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('books_readers', sa.Column('reader_id', sa.Integer(), nullable=True))
    op.drop_constraint('books_readers_books_id_fkey', 'books_readers', type_='foreignkey')
    op.drop_constraint('books_readers_readers_id_fkey', 'books_readers', type_='foreignkey')
    op.create_foreign_key(None, 'books_readers', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'books_readers', 'readers', ['reader_id'], ['id'])
    op.drop_column('books_readers', 'books_id')
    op.drop_column('books_readers', 'readers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_readers', sa.Column('readers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books_readers', sa.Column('books_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books_readers', type_='foreignkey')
    op.drop_constraint(None, 'books_readers', type_='foreignkey')
    op.create_foreign_key('books_readers_readers_id_fkey', 'books_readers', 'readers', ['readers_id'], ['id'])
    op.create_foreign_key('books_readers_books_id_fkey', 'books_readers', 'books', ['books_id'], ['id'])
    op.drop_column('books_readers', 'reader_id')
    op.drop_column('books_readers', 'book_id')
    # ### end Alembic commands ###
